- HISTORY.md
- src/ddqa/utils/github.py
Was getting an issue with the search query returning more than one result when using the following:
https://api.github.com/search/issues?q=sha%3A441957c74d74d70422f1cde1275acfc3a9970637%2Brepo%3ADataDog%2Fintegrations-core
The fix would change it to:
https://api.github.com/search/issues?q=sha%3A441957c74d74d70422f1cde1275acfc3a9970637%20repo%3ADataDog%2Fintegrations-core
Which returns the correct entry
> Fix github api query

- src/ddqa/widgets/static.py
- tests/utils/test_jira.py
We have two warnings when we run the tests: 
```
========================================================================================================================================================================= warnings summary ==========================================================================================================================================================================
src/ddqa/models/github.py:19
/Users/florent.clarret/go/src/github.com/DataDog/ddqa/src/ddqa/models/github.py:19: PytestCollectionWarning: cannot collect test class 'TestCandidate' because it has a __init__ constructor (from: tests/utils/test_jira.py)
class TestCandidate(BaseModel):
tests/screens/test_configure.py: 21 warnings
tests/screens/test_sync.py: 5 warnings …
```
> Fix warnings

- tests/conftest.py
I use my Yubikey to sign commits, so each time the fixture run I need to touch it. This PR explicitly configure the created repository to avoid signing commits.
I know this solution is not ideal, we should find a way to avoid leaking our own config to the test environment but I did not find a way to do that easily. The config option always load global files.
Note: we have the exact same issue on `ddev`
> Do not sign commits when running the tests

- HISTORY.md
- src/ddqa/screens/status.py
The user does not have the right to change the status of a card if they're not assigned to it
| ![before](https://github.com/DataDog/ddqa/assets/1266346/cbe95ba9-65d7-44ce-ae54-e8b892e97a2d)  |   ![after](https://github.com/DataDog/ddqa/assets/1266346/b9df9fc0-606b-4b34-a1d2-fb3bf86770ed) |
In case you missed it, my user is "Florent Clarret".
I don't really know how to implement a unit test for this though.
https://datadoghq.atlassian.net/browse/AITS-208
> Disable the radio button in the status screen if the user is not assigned to the card

- src/ddqa/app/core.py
- src/ddqa/config/core.py
- src/ddqa/screens/configure.py
- src/ddqa/screens/status.py
- src/ddqa/utils/network.py
Very nit PR to fix some warnings my linter noticed: 
- Use list comprehension when needed
- Remove unused methods
- Use walrus operator
> Fix some linter warnings

- HISTORY.md
- src/ddqa/screens/status.py
- Currently we have a 1:1 mapping between our QA statuses and the Jira statuses
- We only handle 3 QA statuses: To do, In progress, and Done
- Most of the time, this 1:1 mapping works well enough but sometimes teams have several final statuses (i.e. "Won't do")
In this case, the cards appear in the "In progress" box, which is wrong. This also make the progression pourcentage wrong because these cards are considered as "To do", so we never reach 100%
Note: Currently teams never have several initial/in progress statuses. 
- Consider any unknown Jira statuses as Done. This "Done" should be read as "there's nothing else to do with this card, we already dealt with it"
- Add an extra column to the "Done" table called "Info" and print the real status if different from the known "Done" status
- …
> Consider unknown statuses as Done

- HISTORY.md
- src/ddqa/screens/create.py
Sometimes we have some extra spaces in the beginning of the title of the PR. Let's strip the title to drop them
| ![Screenshot 2023-11-14 at 11 57 31](https://github.com/DataDog/ddqa/assets/1266346/7df8f2bd-a3a9-4322-a9fe-ada46158b26a) |  ![Screenshot 2023-11-14 at 11 58 11](https://github.com/DataDog/ddqa/assets/1266346/4828bd65-5740-4c6c-8cf9-bc8917ab48ae)  |
https://datadoghq.atlassian.net/browse/AITS-302
> Strip the PR title in the `create` screen

- src/ddqa/cli/__init__.py
The help message is wrong, the env variable is [DDEV_CACHE](https://github.com/DataDog/ddqa/blob/0785953274439fe00d74b25749744e451c1a4504/src/ddqa/config/constants.py#L11)
https://datadoghq.atlassian.net/browse/AITS-303
> Fix the help message for the `--cache-dir` option

- HISTORY.md
- src/ddqa/utils/github.py
- tests/utils/test_github.py
1. We get [this commit](https://github.com/DataDog/integrations-core/commit/1c7edd04a8c639887b78fb4a49da06ca74ff78df)
2. We call the API with [this API call](https://github.com/DataDog/ddqa/pull/59/files#diff-bc8920013e80017b1a900a2d666449f2f11dbf27f02d750f5b1772a55c2b15beL126) without specifying the PR should be merged
3. We end up with [this PR](https://github.com/DataDog/integrations-core/pull/15993) because they messed up with the rebase and the PR has the commit
Two merged PRs can't have the same commit in their history without having conflicts.
Fix the bug, politely asking for merged PR
https://datadoghq.atlassian.net/browse/AITS-306
> Only retrieve merged PR when fetching them from GitHub

- HISTORY.md
- src/ddqa/screens/create.py
- tests/screens/test_create.py
When we choose which team should QA a PR, we do not display the author of the PR, which could be useful. We have the info so it's pretty cheap to add this info
Display the author with a link to its GitHub profile if we have the info
| ![before](https://github.com/DataDog/ddqa/assets/1266346/1d560730-2f01-4b98-a73d-679ff3af11b7)  |  ![after](https://github.com/DataDog/ddqa/assets/1266346/1247dc0c-042a-4d42-906b-751763191bd4)  |
https://datadoghq.atlassian.net/browse/AITS-307
> Show the author of a PR on the create screen

- HISTORY.md
- src/ddqa/widgets/input.py
- tests/widgets/__init__.py
- tests/widgets/test_input.py
In the create screen we have a couple of switches to choose which team(s) should QA the card. The switch is rather small and the labels are not clickable. I find it pretty annoying and it would be better from a UX perspective to be able to click on the label to toggle the switch
When you click on a team label, it will toggle the corresponding switch
| ![before](https://github.com/DataDog/ddqa/assets/1266346/e3481740-0457-477f-a742-d7ded826e70f)  |  ![after](https://github.com/DataDog/ddqa/assets/1266346/98d5917f-aaf9-41d6-9788-d4a836778c42)  |
I swear I clicked on the labels in the "before" gif. 
https://datadoghq.atlassian.net/browse/AITS-308
> Make the team labels clickable in the create screen

- src/ddqa/app/core.py
- src/ddqa/cache/__init__.py
- src/ddqa/cache/github.py
- src/ddqa/screens/sync.py
- src/ddqa/utils/github.py
- tests/conftest.py
See https://github.com/DataDog/ddqa/pull/64 to see exactly what I'm trying to achieve, but the current PR needs to be merged first to make the second one possible.
We have a cache inside the GitHubRepository class to avoid fetching the same PR from GitHub over and over again. Most of the methods related to the cache are private. I'd need to access this cache from outside.
Disclaimer: I know this is not a perfect solution and one could argue that the outside world should not care about the cache. If you think of a better approach let me know, we could implement that step by step.
- Extract all the cache related functions from the GitHubRepository to a GitHubCache
- Add a new attribute to the GitHubRepository that stores the GitHubCache and make use of it
- Update the rest of the code and …
> Extract the cache functions from the GitHubRepository to its own class

- HISTORY.md
- src/ddqa/screens/create.py
- src/ddqa/utils/github.py
- tests/screens/test_create.py
- tests/utils/test_github.py
- We currently have an option in the `config.toml` file called `ignored_labels`. This option initialises the team selection buttons to False if the PR has these labels
- In our repository, we only QA PRs that do not have some labels. There can be a lot of them. See the video in the show time section. In this video for this given release in integrations-core, we have about 500 PRs and about 350 of them have a `no-changelog` or `skip-qa` label
- Users would like to hide these PRs to be able to focus on the relevant PRs
- Refactor a bit the way we fetch the PRs. Until now, the logic was mainly in the `create` screen. I moved the logic to the github module and created a new method called `get_candidates` that iterates over the commits and yield the relevant PRs so the screen does not need to …
> Filter out the PRs with specific tags

- HISTORY.md
- src/ddqa/cache/github.py
- src/ddqa/models/github.py
- src/ddqa/screens/create.py
- tests/screens/test_create.py
- tests/utils/test_github.py
This PR depends on https://github.com/DataDog/ddqa/pull/63 and needs it to be merged first. I opened the current PR to show exactly why the refactor was needed.
The create screen does not save the assignments the user made. If for some reasons the user closes ddqa and open it again, all the assignments are lost. 
- When the user assigns a team to a given PR, we save this info in the cache we already have
- When we load the screen, we read the PRs from the cache and retrieve the already assigned teams for each PR
| ![before](https://github.com/DataDog/ddqa/assets/1266346/08f8341f-0012-4feb-9ae6-5dff0f1d164b) | ![after](https://github.com/DataDog/ddqa/assets/1266346/c5055955-bda8-4319-aef1-e8abf034d61c)  |
Relates to …
> Save and restore the assigned teams to the PRs in the create screen

- src/ddqa/widgets/input.py
- tests/widgets/test_input.py
In fact [this solution](https://github.com/DataDog/ddqa/pull/62/commits/e3b7b77295c8d2e92dc08bad9e62635173204fad#r1393975760) does not work completely. The Changed event is not correctly propagated back to the screen and we do not update the status in the widget on the left :sad:
| ![before](https://github.com/DataDog/ddqa/assets/1266346/06b4508f-0539-4956-abc8-8afcf680f93d) | ![after](https://github.com/DataDog/ddqa/assets/1266346/d51fb357-a8e7-4741-b33d-55c5b5030c05) |
https://datadoghq.atlassian.net/browse/AITS-308
> Fix a bug that prevents the on_change event to be propagated back to the screen

- HISTORY.md
- docs/config/user.md
- src/ddqa/models/config/auth.py
- tests/data/__init__.py
- tests/data/test_auth.py
Users would like to be able to store their Jira and GitHub credentials in environment variables. 
Load the credentials from the environment variables `DDQA_JIRA_TOKEN`, `DDQA_JIRA_EMAIL`, `DDQA_GITHUB_TOKEN` and `DDQA_GITHUB_USER`
https://datadoghq.atlassian.net/browse/AITS-310
> Configure GitHub and Jira credentials from environment variables

- HISTORY.md
- src/ddqa/screens/create.py
When the screen is too small or if we have too many labels, some of them are hidden and the user can't see them all.
- Add a tooltip on the labels (and also on the title) of a given PR so the user can see them all if some of them are hidden
- Also add a horizontal scroll bar when needed
| ![before](https://github.com/DataDog/ddqa/assets/1266346/8a58c2e1-b953-4c0d-b543-33e60b1d2815)  | ![after](https://github.com/DataDog/ddqa/assets/1266346/1998cdea-f6aa-49eb-9933-b11892628342) |
https://datadoghq.atlassian.net/browse/AITS-207
> Add tooltips in the create screen

- src/ddqa/cache/jira.py
- src/ddqa/utils/jira.py
I have a couple of functionalities around the JiraClient to implement. This PR will be needed in the future.Very similar to this PR https://github.com/DataDog/ddqa/pull/63
The cache is implemented directly inside the client. This makes it a bit harder to see the logic related to the cache and the one related to the client itself.
This PR does not add anything new, I just extract the cache to its own class and make use of it in the client. 
Relates to: 
- https://datadoghq.atlassian.net/browse/AITS-210
- https://datadoghq.atlassian.net/browse/AITS-215
> Extract the cache functions from the JiraClient to its own class

- HISTORY.md
- src/ddqa/screens/sync.py
- src/ddqa/utils/jira.py
- tests/screens/test_sync.py
- tests/utils/test_jira.py
The `sync` command does not check if the users that are specified in https://github.com/DataDog/github-metadata/blob/master/jira.toml are still valid in Jira. This leads us to load users that can not be assigned to QA cards
- At the end of the sync command, fetch the users from Jira and drop the deactivated ones from the list that is cached
| ![before](https://github.com/DataDog/ddqa/assets/1266346/662ea18b-f090-4781-90af-b7a2280e448a) | ![after](https://github.com/DataDog/ddqa/assets/1266346/763d5768-fab4-419f-a12b-a543269a0401) |
https://datadoghq.atlassian.net/browse/AITS-215
> Check the status of the users in Jira in the sync command

- HISTORY.md
- src/ddqa/screens/sync.py
In [this PR](https://github.com/DataDog/ddqa/pull/70) I added a check on Jira users. Thanks to that, I wanted to update the config file to drop the users that are deactivated, but before that I wanted to double check they are not part of the org on GitHub and see their profile on Jira. I had no way to do that easily.
- Add a link to the config file
- Add a link to the GitHub teams
- Add a link to the GitHub and Jira profiles of a deactivated user
| ![before](https://github.com/DataDog/ddqa/assets/1266346/be34e058-4d0b-4a88-9d2f-ba75cb320224) | ![after](https://github.com/DataDog/ddqa/assets/1266346/9940eb34-d0fd-45b3-bf76-78fbd24c71c9) |
- https://datadoghq.atlassian.net/browse/AITS-215
> Add direct links to GitHub and Jira in the sync screen

- pyproject.toml
The [latest release](https://github.com/Textualize/textual/releases/tag/v0.42.0) broke our tests. Pin it for now, I'll have a look later
Created https://datadoghq.atlassian.net/browse/AITS-316 to investigate
> Add a upper bound for the textual dependency

- src/ddqa/cache/github.py
- src/ddqa/utils/github.py
- tests/cache/__init__.py
- tests/cache/test_github.py
- tests/conftest.py
- tests/utils/test_github.py
- Tiny refactor to extract some logic only related to the cache to its own class to avoid having it in the github client itself
- Add more test to the cache itself and update the existing tests accordingly
- This PR does not change the behaviour of the application at all 
- Kinda relates to https://datadoghq.atlassian.net/browse/AITS-314 because I noticed this working on it
> Refactor the GitHub team cache

- LICENSE-3rdparty.csv
We don't use it anymore, see https://github.com/DataDog/ddqa/pull/45
> Remove `textual-autocomplete` from the license file

- pyproject.toml
- tests/screens/test_status.py
A new version of [textual](https://pypi.org/project/textual/) is out 🎉 
- Upgrade and pin the version to 0.42.0
- Fix a unit test to work with this new version
Relates to https://datadoghq.atlassian.net/browse/AITS-316
> Bump the textual version to 0.42.0

- pyproject.toml
Pin all the dependencies to avoid breaking the application unexpectedly. I think we can rely on dependabot and the CI to keep our deps up-to-date, our test suite starts to get robust enough to catch most of the issues.
> Pin the dependencies

- .github/dependabot.yml
I [pinned the deps](https://github.com/DataDog/ddqa/pull/80) so I'm configuring dependabot to run at least once a week to notify us of new versions sooner
> Run dependabot at least once a week

- HISTORY.md
- src/ddqa/cli/create/__init__.py
- src/ddqa/models/config/app.py
- src/ddqa/screens/create.py
- src/ddqa/utils/github.py
- tests/cli/config/test_show.py
- tests/utils/test_github.py
Right now we can exclude PRs that have specific labels in the `create`. We do not have an option to only show PRs that have a specific tag (for instance, a `team` tag).
- Add a new parameter to the `create` command to add as many labels as we want
- Use these labels to filter the PRs
- Optionally, if the parameter is not passed, check the user config for the `pr_labels` option and use it.
| ![before](https://github.com/DataDog/ddqa/assets/1266346/31e193cc-85a9-4a38-a05b-6b5e52d272c2) | ![after](https://github.com/DataDog/ddqa/assets/1266346/0fececb0-8861-4dd6-b3c5-5c102fe74f49) |
https://datadoghq.atlassian.net/browse/AITS-320
> Add a `pr_labels` option to the create command

- src/ddqa/app/core.py
- src/ddqa/cli/__init__.py
- src/ddqa/cli/create/__init__.py
- src/ddqa/cli/sync/__init__.py
- src/ddqa/screens/configure.py
- src/ddqa/screens/create.py
- src/ddqa/screens/sync.py
- tests/common.py
- tests/conftest.py
- tests/screens/test_create.py
- tests/screens/test_sync.py
- We mainly rely on labels on PR to pre-assign Jira cards, so the RM does not have to go through a long list of PRs manually.
- This process is now reliable enough to allow us to trigger the creation of the cards automatically without requiring the user to click on the various buttons in the UI.
Ultimately we want to be able to run this in the CI.
- Add an `--auto` flag to to allow users to automatically trigger the various events to create the QA cards.
- This flag is used in several cases: 
1. `ddqa --auto sync` will automatically close the window at the end of the process.
2. `ddqa --auto create` will tirgger the cards creation automatically. If a `sync` is required, the window will be automatically closed once finished.
For now, `ddqa` does not talk a lot. We will need to add more …
> Add an `auto_mode` option to automatically create the QA cards

- HISTORY.md
- src/ddqa/app/core.py
- src/ddqa/cli/config/__init__.py
- src/ddqa/cli/config/set.py
- src/ddqa/config/core.py
- src/ddqa/config/utils.py
- tests/cli/config/test_set.py
- tests/config/__init__.py
- tests/config/test_core.py
- The configuration is stored in a file that we can edit with `ddqa config edit`
- The only way to modify this file is to do it manually or using the `configure` screen
- We can't do it from the CLI, to configure it in the CI for instance
- Add a `ddqa config set <key> <value>` command to be able to modify config option directly from the CLI
Related to https://datadoghq.atlassian.net/browse/AITS-322
> Add a `config set` command to update the config file

- src/ddqa/models/github.py
- src/ddqa/screens/create.py
- src/ddqa/utils/github.py
- tests/screens/test_create.py
- tests/utils/test_github.py
- When we try to create the cards for a PR that was opened by a GitHub app, the app crashes because we manually create the URL to its profile, it contains `[]`, which breaks the link.
- Get the URL to the author profile using the `html_url` attribute, which works for both "real" users and GitHub Apps
> Use the `html_url` attribute to build the URL for the author

- HISTORY.md
- src/ddqa/screens/sync.py
- tests/screens/test_sync.py
`ddqa` relies on a mapping between github users <-> jira users. In our case, this mapping is stored in https://github.com/DataDog/github-metadata/blob/master/jira.toml
A recent PR opened in the `github-metadata` repository added a new GitHub user linked to an already existing Jira user. Namely [here](https://github.com/DataDog/github-metadata/pull/28), `Kyle-Neale` was added but with `steven91`'s Jira user. 
This duplicate produces an error later on when we call the Jira API because we request two times the same user in the same request. 
This PR adds a new validation before we start calling the Jira API to make sure we do not have duplicate Jira users. If there's a duplicate, it will be printed and we will stop the execution because we can't decide which one is the right one.
We should …
> Verify that no duplicated Jira users are found in the config
